### ISSUE TITLE
CLI use failed

### ISSUE THREAD

**Issue by jtara1** [kgryte/markdown-to-restructuredtext#4]
I'm unfamiliar with JS. Had to `apt install nodejs-legacy` to use your library / package via the command line.

```
j@j-pc ~/_Github-Projects/get_media_files $ md2rst README.md
/usr/local/lib/node_modules/markdown-to-restructuredtext/bin/cli:100
		throw error;
		^

Error: Command failed: /bin/sh -c pandoc --from=markdown --to=rst --output=/tmp/890e5635-8a22-49e3-8a68-e85c8b6de03d /home/j/_Github-Projects/get_media_files/README.md
/bin/sh: 1: pandoc: not found

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

```

**Comment by kgryte** [comment]
Do you have `pandoc` installed? According to the error message, `pandoc` is not installed on your system.

Re: `nodejs`. You should follow the installation instructions on the official Node.js website. Installing via `apt` may not give you either an up-to-date installation or a "standard" installation.

In any event, if you are unfamiliar with JS, I would suggest just using `pandoc` directly. The code in this repository is oriented toward Node.js developers needing to convert Markdown to RestructuredText, say, from within a Node.js application. Under the hood, the library code just shells out to `pandoc`, as seen in the error message above.

Hope that helps! :)
