### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by guettli** [kgryte/markdown-to-restructuredtext#6]
Please tell us the state of the project.

The last update is several months old.

What do you suggest for people who want to convert documents?

**Comment by kgryte** [comment]
TMK the project works. What else do you want me to tell you?

Updates/commits are weak indicators of the "state" of a project. I wrote it. It worked. It does not need updates, unless there are bugs or have been breaking changes to dependencies of which I am not aware.

If you know of bugs, etc, PRs are open.

**Comment by guettli** [comment]
Good news. Thank you.
